### ISSUE TITLE
Add a LICENSE to allow use in open-source software

### ISSUE THREAD

**Issue by seshrs** [eecs280staff/unit_test_framework#31]
A student in the EECS 280 Spring Piazza wondered whether they could use this testing framework for their personal project. @CarsonHoffman pointed out that since this repository doesn't include a LICENSE, it can't safely be used in an open-source project.

Perhaps consider releasing this framework for personal use with a license (like the MIT license)?

**Comment by awdeorio** [comment]
+1 MIT license.  I think @james-perretta and @amirkamil were the original authors, so they should weigh in.

**Comment by james-perretta** [comment]
Absolutely! My (and I assume Amir's too) original intent was for this to be open source. I don't have any objections to MIT license.
