### ISSUE TITLE
TestFailure::set_test_name() is unused

### ISSUE THREAD

**Issue by james-perretta** [eecs280staff/unit_test_framework#36]
Suggest removing that function and removing `"In test " << test_name_m << ",` from `TestFailure::print`.

**Comment by amirkamil** [comment]
Proposal: print out the text of the assertion instead, e.g.
```
** Test case "string_uneq4": FAIL
In ASSERT_EQUAL("spam", string("egg")), line 31: 
spam != egg
```
Thoughts?

**Comment by james-perretta** [comment]
That sounds good to me. Am I correct in saying this would just add a string parameter to `assert_equal` and co. and add a member var to `TestFailure`?

**Comment by amirkamil** [comment]
> That sounds good to me. Am I correct in saying this would just add a string parameter to `assert_equal` and co. and add a member var to `TestFailure`?

Yup. See PR #37 for full details.
