### ISSUE TITLE
Possible to add lest strict test matching?

### ISSUE THREAD

**Issue by Rippletank** [eecs280staff/unit_test_framework#44]
Thank you for this very elegant framework. I made a small change to work better for my use and thought it might be useful to share.

In function get_test_names_to_run I replaced:

```
`        else{
            test_names_to_run.push_back(argv[i]);
        }`
```

with:

```
`       else if (strict_mode)
        {
            test_names_to_run.push_back(argv[i]);
        }
        else
        {
            for (auto test : tests_)
            {
                if (test.first.rfind(argv[i],0) == 0)
                {
                    test_names_to_run.push_back(test.first);
                }
            }
        }`
```

Along with some "-s" or "--strict" switches following the pattern of the quiet_mode. 

It matches tests whose name starts with the argument. This allows running small groups of tests based on the first part of the name. For example, specifying basic_clock matches all test for the basic clock.

I'm using the framework to test some C++ classes on desktop before deploying to an embedded system which is part of a side project. Day job is with C# so not confident to put in pull request etc. I do believe this is C++11 compatible though?

Edit: BTW got the rfind code from: [[](url)](https://stackoverflow.com/questions/1878001/how-do-i-check-if-a-c-stdstring-starts-with-a-certain-string-and-convert-a)

**Comment by amirkamil** [comment]
PR #53 implements a more general solution using regular expressions. If you want all test cases that contain "basic_clock", run:
```
$ ./test-executable -e ".*basic_clock.*"
```
