### ISSUE TITLE
Showing more clearly differences with ASSERT_EQUAL

### ISSUE THREAD

**Issue by Zalanshah64** [eecs280staff/unit_test_framework#55]
During p2, I ran into a student who had an output that looked something like this:

![image](https://github.com/eecs280staff/unit_test_framework/assets/85178109/5d018fe4-2459-44fc-b32c-a7a1072651a3)

At first glance, it's pretty much impossible to tell what the actual difference is, and it took me a moment to stare at their code and understand what was going on: they didn't include a space after the last column before each new row got printed.

Minor things like this can be very easy to miss, and for students new to programming, can be a very subtle bug to catch.

Consider if the unit test framework automatically did the following:

- Replace all spaces with the character `
- Replace all instances of `\t` with the character `~`

Then, the student's output would look as follows:

![image](https://github.com/eecs280staff/unit_test_framework/assets/85178109/6afdb198-dd19-456c-8490-e6f5a8e46fae)

It's much easier, then, to see that the student removed the extra space at the end of each row. Implementing this using a basic regex could help students see the differences in things much more easily.

Additionally, we could consider making use of some sort of sdiff tool to show a side-by-side difference between the two values; however, I'm unsure whether sdiff capability would be particularly helpful in any of the future projects, as I can't remember anywhere that may require you to print multiple lines to an arbitrary output stream in one function.

It's also important to note that I picked ` and ~ arbitrarily, as I looked for characters not used in our projects that would also be likely to print correctly on most terminals (since they're ASCII characters). Other options for display may be more intuitive/easier to read and understand (I looked at _ ? and @ as other potential characters for use).

**Comment by amirkamil** [comment]
The unit-test framework just prints each argument to stdout using whatever stream-insertion is implemented for the respective types. It is not a diff utility, nor do I think we want to take that on.

I would tell students to add their own prints (e.g. to separate files), and then use the diff utility of their choice to figure out what is different.
